import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import '../profile/profile_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'cost_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'cost_model.g.dart';

@freezed
class CostModel with _$CostModel {
  const factory CostModel({
    int? value,
    String? etd,
    String? note,
  }) = _CostModel;

  factory CostModel.fromJson(Map<String, Object?> json) =>
      _$CostModelFromJson(json);
}