import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import '../profile/profile_model.dart';
import 'courier_cost_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'courier_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'courier_model.g.dart';

@freezed
class CourierModel with _$CourierModel {
  const factory CourierModel({
    String? code,
    String? name,
    List<CourierCostModel>? costs,
  }) = _CourierModel;

  factory CourierModel.fromJson(Map<String, Object?> json) =>
      _$CourierModelFromJson(json);
}