// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import '../address/address_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'profile_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'profile_model.g.dart';

@freezed
class ProfileModel with _$ProfileModel {
  const factory ProfileModel({
    required String id,
    String? username,
    String? email,
    String? phone,
    @JsonKey(name: 'address_id') int? addressId,
    AddressModel? address,
    String? avatar_url,
    bool? isSeller,
    bool? isAdmin,
    String? nim,
    int? saldo,

  }) = _ProfileModel;

  factory ProfileModel.fromJson(Map<String, Object?> json) =>
      _$ProfileModelFromJson(json);
}
